activity/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('fuxing.activity.views',
    url(r'^info/$|^info/cn/$','info',name='info'),
    url(r'^admin/$|^admin/cn/$','admin',name='admin'),
    url(r'^getall_activities/$|^cn/$','getall_activities',name='getall_activities'),
    url(r'^$|^cn/$','activity',name='activity'),
	)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),
                       url(r'^portal/', include('fuxing.portal.urls')),
                       url(r'^activity/', include('fuxing.activity.urls')),
                       url(r'^room/', include('fuxing.room.urls')),
                       )

#home
urlpatterns += patterns('fuxing.portal.views',
                       url(r'^$|^cn/$','home', name='home'),
                      )

activity/models.py
# coding: utf-8
from django.db import models
import datetime

class Activity(models.Model):
    activityname = models.CharField(max_length=200, verbose_name='ActivityName')
    date_created = models.DateTimeField('date', default=datetime.datetime.now)
    pic_intro = models.CharField(max_length=50, verbose_name='Pic_introduction', null=True, blank=True)
    url_link = models.CharField(max_length=50, verbose_name='Url_link', null=True, blank=True)
    txt_intro = models.TextField(max_length=100, verbose_name='txt_introduction', null=True, blank=True)
    addition = models.TextField(max_length=200, verbose_name='addition', null=True, blank=True)

    class Meta:
        verbose_name = u'活动'
        verbose_name_plural = u'活动'
        app_label = "activity"
        ordering = ['-date_created']

    def __unicode__(self):
        return u'[Activity:%s]' % self.activityname

activity/forms.py
import logging
from django import forms
from intemass.portal.models import SProfile

logger = logging.getLogger(__name__)

room/forms.py
#coding=utf-8
import logging
from django import forms
from fuxing.room.models import Room

logger = logging.getLogger(__name__)

class RoomsreserveForm(forms.Form):
    def __init__(self,*args,**kwargs):
        super(RoomsreserveForm,self).__init__(*args,**kwargs)
        rooms = Room.objects.all()
        rm = [(r.id,r.roomname) for r in rooms]
        self.fields['roomname'] = forms.ChoiceField(choices=rm,label="Roomname")
    #roomname = forms.ChoiceField(choices=rm,label="Roomname")
    begin_date = forms.DateTimeField()
    end_date = forms.DateTimeField()
    customer_name = forms.CharField(label = 'customer_name',max_length=30,
            widget = forms.TextInput())
    phone = forms.CharField(label = 'phone',max_length=30,
            widget = forms.TextInput())
    cellphone = forms.CharField(label = 'cellphone',max_length=30,
            widget = forms.TextInput())
    email = forms.EmailField(label = 'cellphone',max_length=30,
            widget = forms.TextInput(),
            error_messages={'required':u'邮箱不能为空', 'invalid':u'请输入有效邮箱'})
    def clean_roomname(self):
        roomname_id = self.cleaned_data['roomname']
        if roomname_id == None:
            raise forms.ValidationError('Invalid roomname!')
        return roomname_id

'''
class ClassDetailForm(forms.Form):
    def __init__(self,*args,**kwargs):
        teacher = kwargs.pop('teacher')
        super(ClassDetailForm,self).__init__(*args,**kwargs)
        if teacher:
            classrooms = teacher.classrooms.all()
            cs = [(-1,"New Class")] + [(c.id,c.roomname) for c in classrooms]
            self.fields['classid'] = forms.ChoiceField(choices=cs,label="ClassNo.")
            self.fields['stulist'].required = False

    classid = forms.ChoiceField(label="ClassNo.")
    classname = forms.CharField(label = "Class Name",max_length = 30)
    volume = forms.CharField(label = "Class Volume",max_length = 30)
    stulist = forms.CharField(label = "stulist")

    def clean_stulist(self):
        stulist = self.cleaned_data['stulist']
        logger.info("stulist:%s" % stulist)
        if stulist == '':
            return []
        elif ',' in stulist:
            studentids = stulist.split(',')
        else:
            studentids = [stulist]
        logger.info("studentids:%s" % studentids)
        students = []
        for sid in studentids:
            logger.info("sid:%s" % sid)
            try:
                student = SProfile.objects.get(user__id=int(sid))
            except:
                continue
            students.append(student)
        return students
'''

activity/views.py
import logging
from django.shortcuts import render_to_response
from django.template import RequestContext
from fuxing.activity.models import Activity

logger = logging.getLogger(__name__)

def info(request):
    if request.method == "POST":
        return render_to_response('activity_info.html', context_instance=RequestContext(request))
    else:
        activity_id = request.GET.get('id')
        print "!!!!!!!!!!!!!!!!"+str(activity_id)
        activity = Activity.objects.get(id=activity_id)
        txt_intro = activity.txt_intro.replace('\n', '</br>')
        return render_to_response('activity_info.html', {'activity': activity, 'txt_intro': txt_intro}, context_instance=RequestContext(request))

def admin(request):
    return render_to_response('activity_admin.html', context_instance=RequestContext(request))

def activity(request):
    return render_to_response('activity.html', context_instance=RequestContext(request))

def getall_activities(request):
    logger.info("Getting all activities")
    activities = Activity.objects.all()
    print activities
    for a in activities:
        print a.date_created
    response = render_to_response('getall_activities.json',
                                  {'activities': activities},
                                  context_instance=RequestContext(request))
    response['Content-Type'] = 'text/plain; charset=utf-8'
    response['Cache-Control'] = 'no-cache'
    return response




'''
import logging
from intemass.classroom.models import Classroom
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template import RequestContext
from intemass.portal.models import SProfile
from intemass.classroom.forms import ClassDetailForm
from django.contrib.auth.decorators import permission_required
from django.contrib import messages
from portal.common import getTpByRequest
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.utils import simplejson

logger = logging.getLogger(__name__)


def __getGroupName(request):
    groups = request.user.groups.all()
    if groups and len(groups) > 0:
        return groups[0].name
    else:
        return None


def __getClassroom(classid, isCreate=False):
    if classid is None or classid == "-1":
        if isCreate:
            return Classroom.objects.create()
        else:
            return None
    return Classroom.objects.get(id=int(classid))


@permission_required('auth.add_user')
def getall(request):
    logger.info("get classroom entry")
    tp, res = getTpByRequest(request, "login")
    if not tp and res:
        return res
    logger.info("tp:%s" % tp)
    try:
        classrooms = tp.classrooms.all()
    except:
        classrooms = []
    logger.info("tp classrooms:%s" % classrooms)
    response = render_to_response('classroom_all.json',
                                  {'classrooms': classrooms},
                                  context_instance=RequestContext(request))
    response['Content-Type'] = 'text/plain; charset=utf-8'
    response['Cache-Control'] = 'no-cache'
    return response


@permission_required('auth.add_user')
def add(request):
    tp, res = getTpByRequest(request, "login")
    if not tp and res:
        return res
    if request.method == 'POST':
        form = ClassDetailForm(request.POST, teacher=tp)
        if form.is_valid():
            classid = form.cleaned_data['classid']
            roomname = form.cleaned_data['classname']
            volume = form.cleaned_data['volume']
            students = form.cleaned_data['stulist']
            classroom = __getClassroom(classid, True)
            classroom.roomname = roomname
            classroom.volume = volume
            logger.info("classid:%s,classroom:%s,students:%s" % (classid, classroom, students))
            #add remove student from classroom
            __updatestuinclassroom(tp, students, classroom)
            classroom.save()
            tp.classrooms.add(classroom)
            messages.add_message(request, messages.SUCCESS,
                                 "%d students has been added to Class %s" % (len(students), classroom.roomname))
            return redirect('/classroom/add?classid=' + str(classroom.id))
        else:
            return render_to_response('classroom_detail.html', {'form': form},
                                      context_instance=RequestContext(request))
    else:
        classid = request.GET.get('classid')
        classroom = __getClassroom(classid)
        logger.info("classroom:%s" % classroom)
        if classid:
            classid_str = str(classid)
        else:
            classid_str = '-1'
        if classroom:
            classname = classroom.roomname
            volume = classroom.volume
        else:
            classname = 'New Class'
            volume = ""
        form = ClassDetailForm(teacher=tp,
                               initial={'classid': classid_str,
                                        'classname': classname, 'volume': volume})
        return render_to_response('classroom_detail.html', {'form': form},
                                  context_instance=RequestContext(request))


def __updatestuinclassroom(teacher, students, classroom):
    try:
        sp = SProfile.objects.filter(teacher=teacher, classroom__in=[classroom, None])
    except Exception, e:
        print e
    else:
        temp = []
        for s in sp:
            if s not in students:
                s.classroom = None
                s.save()
                temp.append(s)
        for stu in students:
            if stu not in temp:
                stu.classroom = classroom
                stu.save()


@permission_required('auth.add_user')
def getstudents(request):
    if request.method == "POST":
        teacher, res = getTpByRequest(request, "login")
        classid = request.POST['classid']
        try:
            view = request.POST['view']
        except:
            view = 0
        logger.info("classid:%s" % classid)
        if classid and classid != '':
            try:
                classroom = Classroom.objects.get(id=int(classid))
            except:
                classroom = None
        else:
            classroom = None
        logger.info("class:%s" % classroom)
        logger.info("teacher:%s" % teacher)

        stu_teacher_list = []
        if not teacher:
            messages.add_message(request, messages.SUCCESS, "%s has no permission" % request.user.username)
        else:
            checkedteachers = []
            if classroom:
                checkedteachers = classroom.tprofile_set.all()
            else:
                checkedteachers.append(teacher)
            logger.info("checkedteacher:%s" % checkedteachers)
            if teacher not in checkedteachers:
                messages.add_message(request, messages.SUCCESS,
                                     "%s has no permission to this classroom:%s"
                                     % (request.user.username, classroom))
            else:
                stu_teacher_list.append(__buildstuofteachertree(teacher, classroom, view))
        response = render_to_response('classroom_getstudents.json',
                                      {'stu_teacher_list': stu_teacher_list,
                                       'tnum': len(stu_teacher_list)},
                                      context_instance=RequestContext(request))
        response['Content-Type'] = 'text/plain; charset=utf-8'
        response['Cache-Control'] = 'no-cache'
        return response


def __buildstuofteachertree(teacher, classroom, view):
    students = SProfile.objects.filter(teacher=teacher)
    logger.info("students:%s" % students)
    teachernode = {'name': teacher.user.username, 'checked': 'true'}
    if view:
        teachernode['disabled'] = 'true'
    else:
        teachernode['disabled'] = 'false'
    studentnodes = []
    for s in students:
        studentnode = {'node': s, 'gender': s.gender, 'sid': s.user.id, 'disabled': 'false'}
        if s.classroom and s.classroom == classroom:
            studentnode['checked'] = 'true'
        elif not s.classroom:
            studentnode['checked'] = 'false'
        else:
            studentnode['disabled'] = 'true'
            studentnode['checked'] = 'false'
        if view:
            studentnode['disabled'] = 'true'
        studentnodes.append(studentnode)
    return [teachernode, studentnodes]


class ClassroomDelete(DeleteView):
    model = Classroom
    success_url = reverse_lazy("deleteview_callback")

    def get_object(self):
        try:
            pk = self.request.POST['classroomid']
        except:
            return None
        return get_object_or_404(Classroom, id=pk)


def classroom_updatename(request):
    logger.info("classroom_updatename...")
    tp, res = getTpByRequest(request, None)
    response_data = {'state': 'failure'}
    if tp:
        classid = request.GET.get("classid").strip()
        roomname = request.GET.get("roomname").strip()
        logger.info("classid:%s,name:%s" % (classid, roomname))
        if classid and roomname and roomname != "":
            if classid == '-1':
                classroom = __getClassroom(classid, True)
                classroom.roomname = roomname
                classroom.save()
                tp.classrooms.add(classroom)
                tp.save()
            else:
                classroom = __getClassroom(classid, False)
                logger.info(" get classroom %s" % classroom)
            if classroom:
                classroom.roomname = roomname
                classroom.save()
                response_data['classid'] = classroom.id
                response_data['roomname'] = classroom.roomname
                response_data['state'] = 'success'
    return HttpResponse(simplejson.dumps(response_data), mimetype="application/json")
'''

activity/templates/activity.html
{% extends "theme_00.html" %}

{% block title %}联客 People Linked{% endblock%}
{% block head %}
<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/core.css">
	<style type="text/css" media="screen">
		#jMonthCalendar .Meeting { background-color: #660099;}
		#jMonthCalendar .Birthday { background-color: #DD00FF;}
		/*#jMonthCalendar #Event_3 { background-color:#0000FF; }*/
	</style>
<script type="text/javascript" src="{{ STATIC_URL }}js/fuxing_activity.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.slidertron-1.1.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jMonthCalendar.cn.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/date.js"></script>
{% endblock %}

{% block inner_content %}
    <div id="banner">
		<div id="slider">
			<div class="viewer">
				<div class="reel">
					<div class="slide"> <img src="{{ STATIC_URL }}images/activities/event01.jpg" width="900" height="500" alt="event" /> </div>
					<div class="slide"> <img src="{{ STATIC_URL }}images/activities/event02.jpg" width="900" height="500" alt="event" /> </div>
                    <div class="slide"> <img src="{{ STATIC_URL }}images/activities/event03.jpg" width="900" height="500" alt="event" /> </div>
                    <div class="slide"> <img src="{{ STATIC_URL }}images/activities/event04.jpg" width="900" height="500" alt="event" /> </div>
                    <div class="slide"> <img src="{{ STATIC_URL }}images/activities/event05.jpg" width="900" height="500" alt="event" /> </div>
					<div class="slide"> <img src="{{ STATIC_URL }}images/activities/event06.jpg" width="900" height="500" alt="event" /> </div>
                    <div class="slide"> <img src="{{ STATIC_URL }}images/activities/event07.jpg" width="900" height="500" alt="event" /> </div>
                    <div class="slide"> <img src="{{ STATIC_URL }}images/activities/event08.jpg" width="900" height="500" alt="event" /> </div>
                </div>
			</div>
		</div>
        <!--
		<script type="text/javascript">
				$('#slider').slidertron({
					viewerSelector: '.viewer',
					reelSelector: '.viewer .reel',
					slidesSelector: '.viewer .reel .slide',
					advanceDelay: 3000,
					speed: 'slow'
				});
		</script>
        -->
	</div>
    
    <div id="page">
    	<div id="jMonthCalendar"></div>
    </div>
{% endblock %}

activity/templates/activity_admin.html
{% extends "base.html" %}

{% block title %}HOME{% endblock%}
{% block head %}
{% endblock %}

{% block content %}

<div id="wrap">
	<div class="container">
	
    <div class="events-admin">
    	<form action="">
        <p>活动名称：<input name="activity_name" type="text" style="width:300px; height:20px;" /></p>
        <p>添加图片：<input type="file" name="activity_piecture" /></p>
        <p>活动描述：</p>
        <p><textarea cols="100" rows="20p" name="activity_text" value=""></textarea></p>
        <p><input type="submit" value="发布新活动"/></p>
        </form>
    </div>
    
    </div>
</div>

{% endblock %}

activity/templates/activity_info.html
{% extends "base.html" %}

{% block title %}HOME{% endblock%}
{% block head %}
{% endblock %}

{% block content %}
<div id="wrap">
	<div class="container">
	
    <div class="events-recent-box">
    <h3><a href="http://event.weibo.com/688220">复兴办公社开幕派对</a></h3>
        <div class="events-recent-content">
        <p>
        <strong>
        2012年11月18日 
        </strong>
        @联客_复兴办公社 － 卢湾区雁荡路107号18楼G座
        </p>
            <div class="events-recent-img">
            <img alt="1111" border="0" height="135" src="/uploads/event/image_url/50/1111.JPG" width="135" />
            </div>
            <div class="events-recent-text">
                <p>{{ txt_intro|safe }}</p>
            </div>
        </div>
    </div>
    
    </div>
</div>
{% endblock %}

activity/templates/activity_old.html
{% extends "base.html" %}

{% block title %}HOME{% endblock%}
{% block head %}
<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}css/calendar.css">
{% endblock %}

{% block content %}
<div id="wrap">
	<div class="container">
    
	<Script LANGUAGE="JavaScript">
	 var months = new Array("一", "二", "三","四", "五", "六", "七", "八", "九","十", "十一", "十二");
	 var daysInMonth = new Array(31, 28, 31, 30, 31, 30, 31, 31,30, 31, 30, 31);
	 var days = new Array("日","一", "二", "三","四", "五", "六");
	 var classTemp;
	 var today=new getToday();
	 var year=today.year;
	 var month=today.month;
	 var newCal;
	 function getDays(month, year) 
	 {
		  if (1 == month) return ((0 == year % 4)  &&  (0 != (year % 100))) ||(0 == year % 400) ? 29 : 28;
		  else return daysInMonth[month];
	 }
	 function getToday() 
	 {
		  this.now = new Date();
		  this.year = this.now.getFullYear();
		  this.month = this.now.getMonth();
		  this.day = this.now.getDate();
	 }
	 function Calendar() 
	 {
		  newCal = new Date(year,month,1);
		  today = new getToday();   
		  var day = -1;
		  var startDay = newCal.getDay();
		  var endDay=getDays(newCal.getMonth(), newCal.getFullYear());
		  var daily = 0;
		  if ((today.year == newCal.getFullYear())  && (today.month == newCal.getMonth()))
		  {
				day = today.day;
		  }
		  var caltable = document.all.caltable.tBodies.calendar;
		  var intDaysInMonth =getDays(newCal.getMonth(), newCal.getFullYear());
		  for (var intWeek = 0; intWeek < caltable.rows.length;intWeek++)
			   for (var intDay = 0;intDay < caltable.rows[intWeek].cells.length;intDay++)
			   {
					var cell = caltable.rows[intWeek].cells[intDay];
					var montemp=(newCal.getMonth()+1)<10?("0"+(newCal.getMonth()+1)):(newCal.getMonth()+1);         
					if ((intDay == startDay)  &&  (0 == daily)){ daily = 1;}
					var daytemp=daily<10?("0"+daily):(daily);
					var d="<"+newCal.getFullYear()+"-"+montemp+"-"+daytemp+">";
					if(day==daily) cell.className="DayNow";
					else if(intDay==6) cell.className = "DaySat";
					else if (intDay==0) cell.className ="DaySun";
					else cell.className="Day";
					if ((daily > 0)  &&  (daily <= intDaysInMonth))
					{
						 cell.innerText = daily;
						 daily++;
					}
					//else if(daily==18)
					//{
							//cell.innerHTML = "<a href="/">开幕派对</a>";
					//}
					else
					{
						 cell.className="CalendarTD";
					}
	  			}
	  document.all.year.value=year;
	  document.all.month.value=month+1;
	 }
	 function lastMonth()
	 {
		  if ((month-1)<0)
		  {
			   month=11;
			   year=year-1;
		  } 
		  else
		  {
			  month=month-1;
		  }
		  Calendar();
	 }
	 function nextMonth()
	 {
		  if((month+1)>11)
		  {
			   month=0;
			   year=year+1;
		  } else
		  {
			  month=month+1;
		  }
		  Calendar();
	 }
	 function setDate() 
	 {
		  if (document.all.month.value<1||document.all.month.value>12)
		  {
			   alert("月的有效范围在1-12之间!");
			   return;
		  }
		  year=Math.ceil(document.all.year.value);
		  month=Math.ceil(document.all.month.value-1);
		  Calendar();
	 }
	function buttonOver()
	{
		 var obj = window.event.srcElement;
		 obj.runtimeStyle.cssText = "background-color:#FFFFFF";
		// obj.className="Hover";
	}
	function buttonOut()
	{
		 var obj = window.event.srcElement;
		 window.setTimeout(function(){obj.runtimeStyle.cssText = "";},300);
	}
	</Script>
    <table class="Calendar" id="caltable">
	<thead>
        <tr align="center" valign="middle"> 
            <td colspan="7" class="Title">
            <a href="javaScript:lastMonth();" title="上一月" Class="DayButton">3</a> 
            <input name="year" type="text" size="4" maxlength="4" onkeydown="if (event.keyCode==13){setDate()}" onkeyup="this.value=this.value.replace(/[^0-9]/g,'')"  onpaste="this.value=this.value.replace(/[^0-9]/g,'')"> 年 
            <input name="month" type="text" size="1" maxlength="2" onkeydown="if (event.keyCode==13){setDate()}" onkeyup="this.value=this.value.replace(/[^0-9]/g,'')"  onpaste="this.value=this.value.replace(/[^0-9]/g,'')"> 月 
            <a href="javaScript:nextMonth();" title="下一月" Class="DayButton">4</a>
            </td>
        </tr>
        <tr align="center" valign="middle"> 
        <Script LANGUAGE="JavaScript">  
        document.write("<TD class=DaySunTitle id=diary >" + days[0] + "</TD>"); 
        for (var intLoop = 1; intLoop < days.length-1;intLoop++) 
            document.write("<TD class=DayTitle id=diary>" + days[intLoop] + "</TD>"); 
        document.write("<TD class=DaySatTitle id=diary>" + days[intLoop] + "</TD>"); 
        </Script>
        </tr> 
	</thead>
    <tbody border=1 cellspacing="0" cellpadding="0" ID="calendar" ALIGN=CENTER ONCLICK="getDiary()">
	<Script LANGUAGE="JavaScript">
	for (var intWeeks = 0; intWeeks < 6; intWeeks++)
	{
		document.write("<TR style='cursor:hand'>");
		for (var intDays = 0; intDays < days.length;intDays++) 
		{
			document.write("<TD class=CalendarTD onMouseover='buttonOver();' onMouseOut='buttonOut();'></TD>");
		}
		document.write("</TR>");
	} 
	</Script>
</tbody>
</table>
	<Script  LANGUAGE="JavaScript">
 		Calendar();
	</Script>

	
    </div>
</div>
{% endblock %}

activity/templates/classroom_detail.html
{% extends "base.html" %}
{% block title %}Class Modification{% endblock%}

{% block head %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/zTreeStyle.css" type="text/css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/zTreeStyle_custom.css" type="text/css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/classroom_detail.css" type="text/css">
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ztree.core-3.1.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ztree.excheck-3.1.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.jeditable.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/django.csrf.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.blockUI.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/classroom_detail.js"></script>
{% endblock %}

{% block content %}
<div class="container_12">
    <div id="content">
        <div class="form" style="height:500px;">
            <h1>Class Information</h1>
            <form id="class_mod_form" class="content" method="post" action="">{% csrf_token %}
                <div id="zTreeBackground">
                    <span id="zTreeHeader">All Students</span>
                    <ul id="students" class="ztree"></ul>
                    <span id="zTreeFooter">Teachers:<span id='tnum' style="width:60px;padding:0 5px;"></span>, Students:<span id='snum' style="width:60px;padding:0 5px;"></span></span>
                </div>
                <div style="width:250px;float:left;padding-top:2em;">
                    <p>
                    <label for="id_classid"  style="width:100px;margin-left:2px;">ID:</label>
                    {{ form.classid }}
                    {%if form.classid.errors %}
                    {% for error in form.classid.errors %}
                    <div class="warning">{{ error }}</div>
                    {% endfor %}
                    {% endif %}
                    </p>
                <p>
                <label for="id_classname" style="width:100px;margin-left:2px;">Name:</label>
                {{ form.classname }}
                <span id="classnameedit" type="text" maxlength="100" class="editable" style="display:block;width:140px;float:left;padding:3px 0 0 3px;"></span>
                {%if form.classname.errors %}
                {% for error in form.classname.errors %}
                <div class="warning">{{ error }}</div>
                {% endfor %}
                {% endif %}
                </p>

                <p>
                <label for="id_volume" style="width:100px;margin-left:2px;">Volume:</label>
                {{ form.volume }}
                {%if form.volume.errors %}
                {% for error in form.volume.errors %}
                <div class="warning">{{ error }}</div>
                {% endfor %}
                {% endif %}
                </p>

                <p style="display:none;">
                {{form.stulist}}
                </p>
                <p style="clear:both;width:250px;">
                <a href=javascript:submitform() class="greenBtn" id="button" style="float:right;margin-top:5em;">Save</a>
                </p>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="messages_div" style="display:none">
    {% if messages %}
    {% for message in messages %}
    <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
    {% endfor %}
    {% endif %}
</div>

{% endblock %}